export const products = [
  {
    id: 1,
    name: "Toothbrush",
    category: "Personal Care & Hygiene",
    mrp: 100,
    currentPrice: 70,
    rating: 5,
    img: "https://images.unsplash.com/photo-1617984161716-189c889bd474?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRvb3RoYnJ1c2h8ZW58MHx8MHx8fDA%3D",
    description:
      "This eco-friendly bamboo toothbrush is designed to keep your teeth clean while helping the planet. Its biodegradable handle and soft bristles make it safe for your gums and sustainable for the environment.",
    features: [
      "Made from biodegradable bamboo",
      "Soft bristles gentle on gums",
      "Reduces plastic waste",
      "Lightweight and durable",
    ],
  },
  {
    id: 2,
    name: "Jute Bag",
    category: "Home & Living",
    mrp: 350,
    currentPrice: 250,
    rating: 3,
    img: "https://media.istockphoto.com/id/1471827946/photo/coffee-beans-on-a-jute-background-with-copy-space.jpg?b=1&s=612x612&w=0&k=20&c=XuQiEudcpy3AKTLo0Wy-JdFJJA3gMms0w38g-btxkYI=",
    description:
      "Strong, reusable, and stylish, this jute bag is the perfect replacement for plastic carriers. With natural fibers and a spacious design, it’s ideal for groceries, books, or everyday essentials.",
    features: [
      "Made with 100% natural jute fibers",
      "Reusable and eco-friendly",
      "Durable enough to carry heavy loads",
      "Spacious and versatile design",
    ],
  },
  {
    id: 3,
    name: "Cutlery Set",
    category: "Kitchen & Dining",
    mrp: 400,
    currentPrice: 300,
    rating: 4,
    img: "https://images.pexels.com/photos/5507645/pexels-photo-5507645.jpeg",
    description:
      "Say goodbye to disposable plastics with this reusable wooden cutlery set. Lightweight yet sturdy, it’s perfect for home, office lunches, or travel.",
    features: [
      "Reusable and sustainable",
      "Lightweight and portable",
      "Durable wooden design",
      "Easy to clean and maintain",
    ],
  },
  {
    id: 4,
    name: "Cutting Board",
    category: "Kitchen & Dining",
    mrp: 500,
    currentPrice: 380,
    rating: 4,
    img: "https://media.istockphoto.com/id/184289543/photo/wooden-bread-cutting-board-isolated-on-white-knifes-cuts-visible.jpg?b=1&s=612x612&w=0&k=20&c=kn6TcVP5Q17CdtuJmSOfHGiWFPUiaK4NO0hn434wWlI=",
    description:
      "A sturdy wooden cutting board designed to last. It’s gentle on knives, easy to clean, and doubles as a stylish serving tray for bread, cheese, or fruits.",
    features: [
      "Crafted from premium quality wood",
      "Gentle on knives",
      "Doubles as a serving tray",
      "Durable and easy to clean",
    ],
  },
  {
    id: 5,
    name: "Water Bottle",
    category: "Travel & Outdoors",
    mrp: 700,
    currentPrice: 560,
    rating: 5,
    img: "https://media.istockphoto.com/id/1324231979/photo/blank-stainless-steel-double-wall-workout-bottle.jpg?b=1&s=612x612&w=0&k=20&c=ZGqymCN41LUMGjhlN79tQLpq5dNVfoY11IWUyRgdiXc=",
    description:
      "This sleek stainless steel water bottle keeps drinks cold for up to 24 hours and hot for up to 12. Perfect for workouts, travel, or daily hydration without single-use plastics.",
    features: [
      "Double-wall insulation",
      "Keeps drinks hot or cold for hours",
      "Durable stainless steel body",
      "Reusable and eco-friendly",
    ],
  },
  {
    id: 6,
    name: "Glass Cup",
    category: "Home & Living",
    mrp: 250,
    currentPrice: 180,
    rating: 4,
    img: "https://media.istockphoto.com/id/466234073/photo/glass-of-water-isolated-on-a-white-background.jpg?b=1&s=612x612&w=0&k=20&c=UVYEU2z6uT0gtYV96vIns5Sp8k8TwOv1f_7ButHT3r0=",
    description:
      "A classic reusable glass cup with a sleek design. Perfect for daily drinks like water, juices, coffee, or smoothies without any harmful plastics.",
    features: [
      "Made from durable glass",
      "Reusable and dishwasher-safe",
      "Elegant minimalist design",
      "Great for hot and cold drinks",
    ],
  },
  {
    id: 7,
    name: "Spatula Set",
    category: "Kitchen & Dining",
    mrp: 150,
    currentPrice: 95,
    rating: 3,
    img: "https://media.istockphoto.com/id/1202884200/photo/some-wooden-spatula-isolated-on-white-background.jpg?b=1&s=612x612&w=0&k=20&c=YnXw5C4WzBMLTi2T0iKZQox16j7YC0JfczY8f7Dw9E8=",
    description:
      "An eco-friendly spatula set made of durable wood. Heat-resistant and safe for nonstick cookware, making cooking easy and sustainable.",
    features: [
      "Eco-friendly wooden design",
      "Heat resistant",
      "Safe for nonstick cookware",
      "Long-lasting and durable",
    ],
  },
  {
    id: 8,
    name: "Paper Bags",
    category: "Home & Living",
    mrp: 200,
    currentPrice: 120,
    rating: 2,
    img: "https://media.istockphoto.com/id/1086227660/photo/blank-shopping-bag-mock-up-on-isolated-white-background-3d-illustration.jpg?b=1&s=612x612&w=0&k=20&c=6R7FXOAUm3civuCqV2Fl5vvZWP5-V5sl_dl0NlU6uD4=",
    description:
      "Strong and recyclable paper bags designed to replace harmful plastic carry bags. Great for groceries, takeaways, or gifting.",
    features: [
      "Made from recycled paper",
      "Reusable and recyclable",
      "Eco-friendly alternative to plastic",
      "Lightweight yet durable",
    ],
  },
  {
    id: 9,
    name: "Cork Wallet",
    category: "Fashion & Lifestyle",
    mrp: 600,
    currentPrice: 420,
    rating: 3,
    img: "https://media.istockphoto.com/id/531824453/photo/wooden-spoon-fork-and-other-kitchen-tools.jpg?b=1&s=612x612&w=0&k=20&c=8LXCCZFzRqL9IzsyPFY5fuefFcXys9KYKvpK11zGwwI=",
    description:
      "A stylish cork wallet made from natural cork oak bark. Lightweight, vegan, and sustainable while still being durable and functional.",
    features: [
      "Made from renewable cork",
      "Lightweight and slim design",
      "Durable and long-lasting",
      "Vegan and cruelty-free",
    ],
  },
  {
    id: 10,
    name: "Cotton T-Shirt",
    category: "Fashion & Lifestyle",
    mrp: 800,
    currentPrice: 640,
    rating: 5,
    img: "https://media.istockphoto.com/id/1345934516/photo/natural-organic-cotton-t-shirts-and-cotton-plant-flowers-on-white-table-eco-clothes-fashion.jpg?b=1&s=612x612&w=0&k=20&c=KOUfh9Oq_6W0e6opzZ9RcCXHUzQBBUGRv2XtbqMYOhg=",
    description:
      "This organic cotton t-shirt is breathable, soft, and comfortable for all-day wear. A sustainable wardrobe essential that pairs with anything.",
    features: [
      "Made from 100% organic cotton",
      "Breathable and soft fabric",
      "Durable stitching for long wear",
      "Eco-friendly and stylish",
    ],
  },
  {
    id: 11,
    name: "Wooden Toys",
    category: "Kids & Baby",
    mrp: 900,
    currentPrice: 630,
    rating: 3,
    img: "https://media.istockphoto.com/id/182414564/photo/colorful-didactic-wooden-train-toy-for-preschool-aged-kids.jpg?b=1&s=612x612&w=0&k=20&c=jmkNoaKAsF_2WBGvtVzky9EZWMe6whw7w4kXt1ihjaQ=",
    description:
      "Safe and colorful wooden toys designed to spark creativity and imagination in kids. Non-toxic and eco-friendly, perfect for little hands.",
    features: [
      "Made from natural wood",
      "Non-toxic and safe for kids",
      "Bright and engaging colors",
      "Encourages creativity and learning",
    ],
  },
  {
    id: 12,
    name: "Solar Power Bank",
    category: "Travel & Outdoors",
    mrp: 2000,
    currentPrice: 1700,
    rating: 5,
    img: "https://media.istockphoto.com/id/1406845977/photo/portable-solar-panel-charges-a-tablet-on-a-tree-stump-in-a-summer-day.jpg?b=1&s=612x612&w=0&k=20&c=Mo8x9DTK3GXzU0wbh6qTiGsxxWnWzJtU71Lak2j0KUo=",
    description:
      "Never run out of power on your adventures with this solar power bank. Recharge using sunlight and stay connected anywhere you go.",
    features: [
      "Rechargeable via solar energy",
      "Portable and travel-friendly",
      "High-capacity battery",
      "Perfect for camping and outdoors",
    ],
  },
];
